# Tomcat 配置
server:

  tomcat:
    uri-encoding: UTF-8

# Spring 配置
spring:

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

ribbon:
  eager-load:
    enabled: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: false
  ConnectTimeout: 60000
  ReadTimeout: 20000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.wenliao.cloud.entity.*
  global-config:
    #刷新mapper 调试神器
    refresh: true
    #序列接口实现类配置
    db-config:
      capital-mode: false
      id-type: auto
      field-strategy: ignored
      #驼峰下划线转换
      column-underline: false
      #逻辑删除配置
      logic-delete-value: -1
      logic-not-delete-value: 0
      db-type: mysql
  #自定义填充策略接口实现
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false